create table if not exists public.emociones (
    id integer generated by default as identity primary key,
    nombre varchar(30) not null unique,
    descripcion text,
    intensidad_min varchar(30) not null,
    intensidad_max varchar(30) not null
);

create table if not exists public.temas (
    id integer generated by default as identity primary key,
    nombre varchar(100) not null,
    descripcion text,
    categoria varchar(50),
    emociones_esperadas jsonb
);

create table if not exists public.corpus (
    id integer generated by default as identity primary key,
    id_comment varchar(50) not null unique,
    video_id varchar(50) not null,
    texto_raw text not null,
    texto_limpio text,
    id_emocion integer references public.emociones(id) on delete set null,
    intensidad smallint check (intensidad between 1 and 4),
    id_tema integer not null references public.temas(id) on delete cascade,
    likes integer default 0,
    fecha timestamp
);

create index if not exists idx_corpus_emocion on public.corpus (id_emocion);
create index if not exists idx_corpus_tema on public.corpus (id_tema);
create index if not exists idx_corpus_fecha on public.corpus (fecha);
create index if not exists idx_corpus_video on public.corpus (video_id);

create table if not exists public.temas_training (
    id integer generated by default as identity primary key,
    nombre varchar(100) not null,
    descripcion text,
    categoria varchar(50),
    emociones_esperadas jsonb
);

create table if not exists public.corpus_training (
    id integer generated by default as identity primary key,
    id_comment varchar(50) not null unique,
    video_id varchar(50) not null,
    texto_raw text not null,
    texto_limpio text,
    id_emocion integer references public.emociones(id) on delete set null,
    intensidad smallint check (intensidad between 1 and 4),
    id_tema integer not null references public.temas_training(id) on delete cascade,
    likes integer default 0,
    fecha timestamp
);

create index if not exists idx_training_emocion on public.corpus_training (id_emocion);
create index if not exists idx_training_tema on public.corpus_training (id_tema);
create index if not exists idx_training_video on public.corpus_training (video_id);
create index if not exists idx_training_fecha on public.corpus_training (fecha);