-- ============================================================
-- Fase 5 — Tablas de Predicciones en Producción
-- ============================================================
-- Estas tablas almacenan los resultados del modelo en producción.
-- Son INDEPENDIENTES de las tablas de entrenamiento (corpus, corpus_training).
--
-- Modelo: FalexOne/robertuito-emociones-tiktok
-- Clases: Alegría, Confianza, Miedo, Expectación, Tristeza, Rechazo
-- Umbral: Si confianza máxima < 0.40 → Incierto
-- ============================================================


-- ────────────────────────────────────────────────────────────
-- 1. TEMAS DE ANÁLISIS (producción)
-- ────────────────────────────────────────────────────────────
-- Temas asignados a videos analizados en producción.
-- Separados de la tabla `temas` de entrenamiento.

create table if not exists public.temas_produccion (
    id          bigint generated by default as identity primary key,
    nombre      varchar(150) not null,
    descripcion text,
    categoria   varchar(80),
    created_at  timestamptz default now()
);

create unique index if not exists idx_temas_prod_nombre
    on public.temas_produccion (nombre);


-- ────────────────────────────────────────────────────────────
-- 2. VIDEOS ANALIZADOS
-- ────────────────────────────────────────────────────────────
-- Cada video de TikTok que se analiza se registra aquí.

create table if not exists public.videos_analizados (
    id                  bigint generated by default as identity primary key,
    url                 text not null,
    video_id_tiktok     varchar(80) unique,       -- ID nativo del video en TikTok
    titulo              text,
    id_tema             bigint references public.temas_produccion(id) on delete set null,
    tema_auto_generado  boolean default false,     -- true si el tema fue detectado automáticamente
    total_comentarios   int default 0,             -- total de comentarios descargados
    total_analizados    int default 0,             -- total procesados por el modelo
    created_at          timestamptz default now()
);

create index if not exists idx_videos_tema
    on public.videos_analizados (id_tema);

create index if not exists idx_videos_created
    on public.videos_analizados (created_at);


-- ────────────────────────────────────────────────────────────
-- 3. PREDICCIONES
-- ────────────────────────────────────────────────────────────
-- Cada fila = 1 comentario analizado por el modelo.
-- Almacena la predicción + los 6 scores individuales.

create table if not exists public.predicciones (
    id                  bigint generated by default as identity primary key,

    -- Relación con video (nullable para análisis individuales sin video)
    id_video            bigint references public.videos_analizados(id) on delete cascade,

    -- Texto del comentario
    texto_original      text not null,
    texto_limpio        text,

    -- Predicción del modelo
    emocion_predicha    varchar(30) not null,       -- Alegría | Confianza | Miedo | Expectación | Tristeza | Rechazo | Incierto
    confianza_maxima    numeric(5,4) not null,      -- 0.0000 — 1.0000
    es_incierto         boolean default false,      -- true cuando confianza_maxima < 0.40

    -- Scores individuales por cada clase (suman ~1.0)
    score_alegria       numeric(5,4) not null default 0,
    score_confianza     numeric(5,4) not null default 0,
    score_miedo         numeric(5,4) not null default 0,
    score_expectacion   numeric(5,4) not null default 0,
    score_tristeza      numeric(5,4) not null default 0,
    score_rechazo       numeric(5,4) not null default 0,

    -- Metadata del comentario original (si está disponible)
    likes               int default 0,
    fecha_comentario    timestamptz,                -- fecha del comentario en TikTok
    id_comment_tiktok   varchar(80),                -- ID del comentario en TikTok

    -- Metadata del análisis
    tipo_analisis       varchar(20) default 'individual',  -- 'individual' | 'batch_video'
    created_at          timestamptz default now()
);

-- Índices para queries del dashboard
create index if not exists idx_pred_emocion
    on public.predicciones (emocion_predicha);

create index if not exists idx_pred_video
    on public.predicciones (id_video);

create index if not exists idx_pred_created
    on public.predicciones (created_at);

create index if not exists idx_pred_incierto
    on public.predicciones (es_incierto);

create index if not exists idx_pred_confianza
    on public.predicciones (confianza_maxima desc);


-- ────────────────────────────────────────────────────────────
-- 4. SESIONES DE ANÁLISIS
-- ────────────────────────────────────────────────────────────
-- Registra cada ejecución de análisis (individual o batch).
-- Útil para timeline y auditoría.

create table if not exists public.sesiones_analisis (
    id                  bigint generated by default as identity primary key,
    id_video            bigint references public.videos_analizados(id) on delete set null,
    tipo                varchar(20) not null,       -- 'individual' | 'batch_video'
    total_procesados    int default 0,
    total_inciertos     int default 0,
    emocion_dominante   varchar(30),                -- emoción más frecuente en la sesión
    confianza_promedio  numeric(5,4),               -- promedio de confianza de la sesión
    duracion_ms         int,                        -- tiempo total de procesamiento
    created_at          timestamptz default now()
);


-- ────────────────────────────────────────────────────────────
-- 5. VISTAS PARA EL DASHBOARD
-- ────────────────────────────────────────────────────────────

-- Vista: KPIs globales
create or replace view public.v_dashboard_kpis as
select
    count(*)::int                                               as total_predicciones,
    count(distinct id_video)::int                               as total_videos,
    count(*) filter (where es_incierto)::int                    as total_inciertos,
    round(
        count(*) filter (where es_incierto)::numeric
        / nullif(count(*), 0) * 100, 1
    )                                                           as pct_inciertos,
    (
        select emocion_predicha
        from public.predicciones
        where not es_incierto
        group by emocion_predicha
        order by count(*) desc
        limit 1
    )                                                           as emocion_dominante
from public.predicciones;


-- Vista: Distribución de emociones (para treemap / barras)
create or replace view public.v_distribucion_emociones as
select
    emocion_predicha,
    count(*)::int                                               as total,
    round(count(*)::numeric / nullif(
        (select count(*) from public.predicciones), 0
    ) * 100, 1)                                                 as porcentaje,
    round(avg(confianza_maxima)::numeric, 4)                    as confianza_promedio
from public.predicciones
where not es_incierto
group by emocion_predicha
order by total desc;


-- Vista: Distribución por tema
create or replace view public.v_distribucion_por_tema as
select
    va.id                                                       as id_video,
    tp.nombre                                                   as tema,
    p.emocion_predicha,
    count(*)::int                                               as total,
    round(avg(p.confianza_maxima)::numeric, 4)                  as confianza_promedio
from public.predicciones p
join public.videos_analizados va on va.id = p.id_video
left join public.temas_produccion tp on tp.id = va.id_tema
where not p.es_incierto
group by va.id, tp.nombre, p.emocion_predicha
order by tp.nombre, total desc;


-- Vista: Sentimiento agregado (positivo / negativo / neutro)
-- Mapeo:
--   Positivo  = Alegría + Confianza
--   Negativo  = Miedo + Tristeza + Rechazo
--   Neutro    = Expectación + Incierto
create or replace view public.v_sentimiento_agregado as
select
    case
        when emocion_predicha in ('Alegría', 'Confianza') then 'Positivo'
        when emocion_predicha in ('Miedo', 'Tristeza', 'Rechazo') then 'Negativo'
        else 'Neutro'
    end                                                         as sentimiento,
    count(*)::int                                               as total,
    round(count(*)::numeric / nullif(
        (select count(*) from public.predicciones), 0
    ) * 100, 1)                                                 as porcentaje
from public.predicciones
group by 1
order by total desc;


-- Vista: Timeline (predicciones por semana)
create or replace view public.v_timeline_semanal as
select
    date_trunc('week', created_at)::date                        as semana,
    emocion_predicha,
    count(*)::int                                               as total
from public.predicciones
where not es_incierto
group by 1, 2
order by semana, total desc;


-- Vista: Top comentarios más confiables
create or replace view public.v_top_confiables as
select
    id,
    texto_original,
    emocion_predicha,
    confianza_maxima,
    likes,
    created_at
from public.predicciones
where not es_incierto
order by confianza_maxima desc
limit 10;


-- ────────────────────────────────────────────────────────────
-- 6. ROW LEVEL SECURITY (RLS)
-- ────────────────────────────────────────────────────────────
-- Habilitamos RLS y creamos políticas de lectura pública
-- para que el dashboard frontend pueda leer sin autenticación.

alter table public.temas_produccion enable row level security;
alter table public.videos_analizados enable row level security;
alter table public.predicciones enable row level security;
alter table public.sesiones_analisis enable row level security;

-- Políticas de lectura pública (anon + authenticated)
create policy "Lectura pública de temas producción"
    on public.temas_produccion for select
    using (true);

create policy "Lectura pública de videos analizados"
    on public.videos_analizados for select
    using (true);

create policy "Lectura pública de predicciones"
    on public.predicciones for select
    using (true);

create policy "Lectura pública de sesiones"
    on public.sesiones_analisis for select
    using (true);

-- Políticas de inserción pública (para que el frontend pueda escribir)
create policy "Inserción pública de temas producción"
    on public.temas_produccion for insert
    with check (true);

create policy "Inserción pública de videos analizados"
    on public.videos_analizados for insert
    with check (true);

create policy "Inserción pública de predicciones"
    on public.predicciones for insert
    with check (true);

create policy "Inserción pública de sesiones"
    on public.sesiones_analisis for insert
    with check (true);


-- ────────────────────────────────────────────────────────────
-- 7. FUNCIONES AUXILIARES
-- ────────────────────────────────────────────────────────────

-- Función: Insertar una predicción individual y retornar el ID
create or replace function public.fn_insertar_prediccion(
    p_texto_original    text,
    p_texto_limpio      text default null,
    p_emocion_predicha  varchar(30) default 'Incierto',
    p_confianza_maxima  numeric(5,4) default 0,
    p_es_incierto       boolean default true,
    p_score_alegria     numeric(5,4) default 0,
    p_score_confianza   numeric(5,4) default 0,
    p_score_miedo       numeric(5,4) default 0,
    p_score_expectacion numeric(5,4) default 0,
    p_score_tristeza    numeric(5,4) default 0,
    p_score_rechazo     numeric(5,4) default 0,
    p_id_video          bigint default null,
    p_tipo_analisis     varchar(20) default 'individual'
)
returns bigint
language plpgsql
as $$
declare
    v_id bigint;
begin
    insert into public.predicciones (
        texto_original, texto_limpio,
        emocion_predicha, confianza_maxima, es_incierto,
        score_alegria, score_confianza, score_miedo,
        score_expectacion, score_tristeza, score_rechazo,
        id_video, tipo_analisis
    ) values (
        p_texto_original, p_texto_limpio,
        p_emocion_predicha, p_confianza_maxima, p_es_incierto,
        p_score_alegria, p_score_confianza, p_score_miedo,
        p_score_expectacion, p_score_tristeza, p_score_rechazo,
        p_id_video, p_tipo_analisis
    )
    returning id into v_id;

    return v_id;
end;
$$;
